name: "low-priority-CCG-visit-RCT CI"

on:
  push:
    branches:
      - master
  pull_request:

env:
  GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/low-priority-CCG-visit-RCT/low-priority-CCG-visit-RCT/outcomes/google-credentials.json

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: "Unit tests"
        run: python test.py
